# Generated by Django 2.2.2 on 2019-06-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_auto_20190619_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_text',
            field=models.TextField(),
        ),
    ]
