# Generated by Django 2.2.2 on 2019-06-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_profile_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friends',
            new_name='follows',
        ),
    ]
