# Generated by Django 2.2.2 on 2019-06-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0014_profile_follows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(to='practice.profile'),
        ),
    ]
